name: Release  PS2-OPL-CFG-Compatibility-Database
on:
  workflow_dispatch:
  repository_dispatch:
  push:
  
jobs:
  Repack_and_Release:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code for release
      uses: actions/checkout@v2
      
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      
    - name: zip Folder For Release
      run: |
        SCH=${GITHUB_SHA::7}
        DATEE=`date '+[%Y-%m-%d]'`
        echo "----PS2-OPL-CFG-Compatibility-Database----">hash.txt
        echo Commit $SCH>>hash.txt
        7z a -t7z -r PS2-OPL-CFG-Compatibility-Database.7z *
    
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: PS2-OPL-CFG-Compatibility-Database-${{ steps.slug.outputs.sha8 }}
        path: |
             PS2-OPL-CFG-Compatibility-Database.7z
    
    - name: delete previous tag/release
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: Latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy pre-release
      uses: softprops/action-gh-release@v1
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fail_on_unmatched_files: true
        files: |
             PS2-OPL-CFG-Compatibility-Database.7z
        name: "Latest PS2-OPL-CFG-Compatibility-Database"
        tag_name: "Latest"
        prerelease: true
    
